### ISSUE TITLE
Front-end fails to build due to missing file

### ISSUE THREAD

**Issue by HanKruiger** [mbudiu-vmw/hiero#120]
When building the front-end (`mvn package` in `web`), the build system mentions a missing file:
```
ERROR in ./rpc.ts
(2,22): error TS6053: File '/Users/hkruiger/Projects/hiero_fresh/web/src/main/webapp/typings/index.d.ts' not found.
   [1] ./rpc.ts 6.61 kB {0} [built] [1 error]
ERROR in ./rpc.ts
(2,22): error TS6053: File '/Users/hkruiger/Projects/hiero_fresh/web/src/main/webapp/typings/index.d.ts' not found.
```
Removing the violating import line (line 2 in `web/src/main/webapp/rpc.ts`) removes this error, and I don't see any problems in the application after that. But I'm not sure if this is a good fix, as the file may need to be imported for a reason(?).

**Comment by mbudiu-vmw** [comment]
@HanKruiger : I have actually pushed a commit to master to solve this.
If you think it does, please close the issue.
(I should not have pushed to master; I should have created a pull request for you to review; next time I will follow the right procedures.)
