### ISSUE TITLE
Setting up Tomcat only works after building the front-end

### ISSUE THREAD

**Issue by HanKruiger** [mbudiu-vmw/hiero#121]
`web/target/web-1.0-SNAPSHOT.war` doesn't exist yet when installing the required software (before building the project). Tomcat should be configured **after** the front-end has been built.

**Comment by mbudiu-vmw** [comment]
You should be able to create the symlink even if the file you link to does not exist.

**Comment by HanKruiger** [comment]
You're right, this is a non-issue. I probably thought it wouldn't work because my tab-autocompletion didn't work.. Sorry!
