### ISSUE TITLE
SplitTable changing the type of columns - causes null exception without converter

### ISSUE THREAD

**Issue by uwieder** [mbudiu-vmw/hiero#46]
After creating a table of Integer columns and splitting it using SplitTable, the columns of the subtables are changed to ObjectArrayColumn. As a result when invoking the column's asDouble() method the default converter from ints to doubles is not invoked. If an explicit converter is not supplied this results in a null exception. Below is a code that generates the bug:

Test
public void createBug() {
    // Creating Int Table
    final SmallTable bigTable = getIntTable(10000, 1);
    // Grabbing the Column
    String colName = bigTable.getSchema().getColumnNames().iterator().next();
    IColumn column  = bigTable.getColumn(colName);
    IMembershipSet memset = bigTable.getMembershipSet();
    IRowIterator iter = memset.getIterator();
    // All seem to work fine
    System.out.println(" printing the double " + column.asDouble(iter.getNextRow(), null));
    System.out.println(" printing the double " + column.asDouble(iter.getNextRow(), null));

    // Splitting the table
    List<SmallTable> tabList = SplitTable(bigTable, 10000);
    // Grabbing the column from  the sub-tables
    ITable subtable = tabList.iterator().next();
    IColumn column1 = subtable.getColumn(colName);
    IMembershipSet memset1 = subtable.getMembershipSet();
    IRowIterator iter1 = memset1.getIterator();

    //Null Exception!!!
    System.out.println(" printing the double " + column1.asDouble(iter1.getNextRow(), null));
    System.out.println(" printing the double " + column1.asDouble(iter1.getNextRow(), null));
}

**Comment by parikg** [comment]
This has been fixed. See test Issue46.
