### ISSUE TITLE
We don't use the NonNull annotations

### ISSUE THREAD

**Issue by mbudiu-vmw** [mbudiu-vmw/hiero#47]
We should change to a workflow that makes use of these annotations.

**Comment by lalithsuresh** [comment]
I vote for using FindBugs.

**Comment by mbudiu-vmw** [comment]
I assigned this to Lalith - to integrate FindBugs in the toolchain, and remove the checker framework.

**Comment by lalithsuresh** [comment]
See https://github.com/mbudiu-vmw/hiero/pull/49
